name: Build and Test
on:
  push:
    branches: [ main, feature-automacao ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '21.0.2'

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '21.0.2'
        maven-version: '3.9.1'
        cache: 'maven'
        
    - name: Install dependencies
      run: mvn -B dependency:go-offline -Dmaven.repo.local=.m2

    - name: Build with Maven
      run: mvn -B clean install -DskipTests=true -e -X

    - name: Run Cucumber tests
      run: mvn -B test -Dtest=RunCucumberTest -Dargs="--headless"
