trname: Java CI with Maven

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.0.18'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.0.18'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean install -DskipTests=true -e -X

      - name: Run tests with Maven
        run: mvn -B test -Dtest=RunCucumberTest test

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: '**/target/surefire-reports/*.xml'
