name: Build and Test
on:
  push:
    branches: [ main, feature-automacao ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - task: Maven@3
      inputs: 
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '11.0.18'
        jdkArchitectureOption: 'x64'
        options: '-DskipTests=true -e -X'
        goals: 'clean install'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '11.0.18'
        jdkArchitectureOption: 'x64'
        goals: 'test'
        options: '-Dtest=RunCucumberTest test'
  
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**target/surefire-reports/*.xml'
        testRunTitle: 'Surefire Test Results'
