name: Build and Test
on:
  push:
    branches: [ main, feature-automacao ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '21.0.2'

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Maven
      run: choco install maven -y

    - name: Check Java and Maven version
      run: |
        java -version
        mvn -version
        
    - name: Install dependencies
      run: mvn -B dependency:go-offline

    - name: Build with Maven
      run: mvn -B clean install -DskipTests=true -e -X

    - name: List test files
      run: |
        echo "Listing test files in src/test"
        Get-ChildItem -Path src/test -Recurse -Filter *.java

    - name: Run Cucumber tests
      run: mvn -B test -Dtest=RunCucumberTest -Dargs="--headless"

    - name: Print Surefire reports
      if: failure()
      run: |
        echo "Printing Surefire reports"
        Get-ChildItem -Path target/surefire-reports -Recurse -Filter *.txt | ForEach-Object { Get-Content $_.FullName }
